version: '2'
services:
  cars_test:    
    image: aksenchyk/fm-cars:build
    environment:
      # codecov.io requires this variables
      - CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM  
      - CIRCLECI=$CIRCLECI
      - CIRCLE_BUILD_NUM = $CIRCLE_BUILD_NUM
      - CIRCLE_NODE_INDEX=$CIRCLE_NODE_INDEX
      - CIRCLE_SHA1=$CIRCLE_SHA1
      - CIRCLE_BRANCH=$CIRCLE_BRANCH
      - CIRCLE_PR_NUMBER=$CIRCLE_PR_NUMBER
      - CIRCLE_PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME
      - CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME
      - CIRCLE_ARTIFACTS=$CIRCLE_ARTIFACTS
    env_file:
      - ./test_.env
    depends_on:      
      - tracker
      - image
      - rabbitmq 
    entrypoint: ./wait-for-it.sh tracker:8080 image:8080 rabbitmq:5672 -s -- npm run test    
  tracker:    
    image: aksenchyk/fm-tracker:latest 
    depends_on: 
      - rabbitmq
    env_file:
      - ./test_.env
    command: npm run dev
  image:
    image: aksenchyk/fm-image:latest
    depends_on: 
      - rabbitmq
    env_file:
      - ./test_.env
    command: npm run dev    
  rabbitmq:
    image: rabbitmq:latest
   